---
image_resource:
  type: docker-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.5'

platform: linux

inputs:
- name: gr-release-develop
- name: cf-acceptance-tests
- name: cfbench-master
  path: src/github.com/teddyking/cfbench

caches:
- path: gr-release-develop/bin
- path: gr-release-develop/pkg
- path: cfbench-master/bin
- path: cfbench-master/pkg

params:
  CF_API:
  CF_USERNAME:
  CF_PASSWORD:
  CF_ORG:
  CF_SPACE:
  CF_ENV:
  CF_ACTION:
  INSTANCES:
  DATADOG_API_KEY:
  DATADOG_APPLICATION_KEY:

run:
  path: gr-release-develop/ci/scripts/cfbench
