---
platform: linux

inputs:
- name: gr-release-develop
- name: cf-acceptance-tests
- name: cfbench-master

caches:
- path: gr-release-develop/bin
- path: gr-release-develop/pkg
- path: cfbench-master/bin
- path: cfbench-master/pkg

params:
  CF_API:
  CF_USERNAME:
  CF_PASSWORD:
  CF_ORG:
  CF_SPACE:
  CF_ENV:
  CF_ACTION:
  INSTANCES:
  WAVEFRONT_TOKEN:

run:
  path: gr-release-develop/ci/scripts/cfbench
