---
image_resource:
  type: registry-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.16'

platform: linux

inputs:
- name: gr-release-develop
- name: cf-acceptance-tests

params:
  CF_DOMAIN:
  CF_USERNAME:
  CF_PASSWORD:
  CF_ORG:
  CF_SPACE:

run:
  path: gr-release-develop/ci/scripts/cfpush
