---
image_resource:
  type: docker-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.10'

platform: linux

inputs:
- name: gr-release-develop

caches:
- path: gr-release-develop/bin
- path: gr-release-develop/pkg

params:
  RACE_DETECTION:
  GINKGO_NODES:
  CONTAINERD_ENABLED: true

run:
  path: gr-release-develop/ci/scripts/containerd
