---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.25'

inputs:
  - name: gr-release-develop

run:
  path: gr-release-develop/ci/scripts/dontpanic-unit
  user: root
