---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.24'

inputs:
- name: gr-release-develop

run:
  path: gr-release-develop/ci/scripts/greenskeeper
