---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.23'

inputs:
- name: gr-release-develop

caches:
- path: gr-release-develop/bin
- path: gr-release-develop/pkg

run:
  dir: gr-release-develop/src/grootfs
  path: make
  args: [go-vet]
