---
image_resource:
  type: registry-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.22'

platform: linux

inputs:
- name: gr-release-develop

caches:
- path: gr-release-develop/bin
- path: gr-release-develop/pkg

params:
  RACE_DETECTION:
  GINKGO_NODES:
  CONTAINERD_ENABLED:
  LOCAL_DEV_RUN:
  PATCH_RUNC:
  CONTAINERD_FOR_PROCESSES_ENABLED:

run:
  path: gr-release-develop/ci/scripts/guardian
