---
platform: windows

resources:
- name: gr-release-develop
  type: git
  source: {uri: "https://github.com/cloudfoundry/garden-runc-release/"}

params:
  WORKAROUND_BRANCH:
run:
  path: powershell
  args:
  - "-ExecutionPolicy"
  - "Bypass"
  - "-File"
  - gr-release-develop/ci/scripts/guardian-windows-workaround.ps1
