---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.14'

inputs:
  - name: gr-release-develop

run:
  path: ci/scripts/root-tests.sh
  dir: gr-release-develop/src/idmapper
  user: root
