---
platform: linux
image_resource:
  type: registry-image
  source:
      repository: concourse/git-resource

inputs:
  - name: gr-release-develop
  - name: gr-release-release

outputs:
  - name: release-merged

run:
  path: gr-release-develop/ci/scripts/merge-release
