---
platform: linux

inputs:
- name: gr-release-develop

caches:
- path: gr-release-develop/bin
- path: gr-release-develop/pkg

params:
  GARDEN_ADDRESS: ""
  ENVIRONMENT: ""
  WAVEFRONT_TOKEN: ""
  WAVEFRONT_URL: https://longboard.wavefront.com/
  WAVEFRONT_METRIC_PREFIX: ""

run:
  path: gr-release-develop/ci/scripts/performance-tests
