---
image_resource:
  type: registry-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.17'

platform: linux

inputs:
- name: gr-release-develop

caches:
- path: gr-release-develop/bin
- path: gr-release-develop/pkg

params:
  GARDEN_ADDRESS: ""
  DATADOG_API_KEY: ""
  ENVIRONMENT: ""

run:
  path: gr-release-develop/ci/scripts/performance-tests
