---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfgarden/garden-ci
    tag: '2.0.11'

inputs:
  - name: gr-release-develop

run:
  path: gr-release-develop/ci/scripts/thresholder
