root = "/var/vcap/data/containerd/root"
state = "/var/vcap/data/containerd/state"
subreaper = true
oom_score = -999

[grpc]
address = "/var/vcap/sys/run/containerd/containerd.sock"

[debug]
address = "/var/vcap/sys/run/containerd/debug.sock"
level = "info"
