- type: replace
  path: /releases/-
  value:
    name: "bpm"
    version: "0.9.0"
    url: "https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.9.0"
    sha1: "0cb3242063c95271c95b62de3a6d07072aff0b29"

- type: replace
  path: /instance_groups/name=garden/jobs/-
  value:
    name: bpm
    release: bpm

- type: replace
  path: /instance_groups/name=garden/jobs/name=garden/properties/bpm?/enabled?
  value: true
