- type: replace
  path: /releases/-
  value:
    name: "bpm"
    version: "0.13.0"
    url: "https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.13.0"
    sha1: "4b6ebfdaa467c04855528172b099e565d679e0f5"

- type: replace
  path: /instance_groups/name=garden/jobs/-
  value:
    name: bpm
    release: bpm

- type: replace
  path: /instance_groups/name=garden/jobs/name=garden/properties/bpm?/enabled?
  value: true
