- type: replace
  path: /releases/-
  value:
    name: "bpm"
    version: "1.0.0"
    url: "https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=1.0.0"
    sha1: "42b95d4a0d6d15dd0b0ead62418ffb56208e2307"

- type: replace
  path: /instance_groups/name=garden/jobs/-
  value:
    name: bpm
    release: bpm

- type: replace
  path: /instance_groups/name=garden/jobs/name=garden/properties/bpm?/enabled?
  value: true
