- type: replace
  path: /releases/-
  value:
    name: "bpm"
    version: "1.0.1"
    url: "https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=1.0.1"
    sha1: "d2265828bac2d62a2c611180da4ced9fc49c546a"

- type: replace
  path: /instance_groups/name=garden/jobs/-
  value:
    name: bpm
    release: bpm

- type: replace
  path: /instance_groups/name=garden/jobs/name=garden/properties/bpm?/enabled?
  value: true

- type: replace
  path: /instance_groups/0/jobs/name=garden/properties/garden/destroy_containers_on_start?
  value: true
