name: ((deployment))

releases:
- name: garden-runc
  version: latest
- name: "bpm"
  version: "1.1.21"
  url: "https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.21"
  sha1: "e8abe19ec186962828de843f8f281cddb6141904"

stemcells:
- alias: stemcell
  os: ((stemcell-os))
  version: latest

instance_groups:
- name: gats
  instances: 1
  vm_type: ((vm))
  networks:
  - name: ((network))
  azs: [((az))]
  stemcell: stemcell
  jobs:
  - name: bpm
    release: bpm
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        debug_listen_address: 0.0.0.0:17013
        log_level: debug
  - name: gats
    release: garden-runc
- name: gpats
  instances: 1
  vm_type: ((vm))
  networks:
  - name: ((network))
  azs: [((az))]
  stemcell: stemcell
  jobs:
  - name: bpm
    release: bpm
  - name: garden
    release: garden-runc
    properties:
      garden:
        listen_network: tcp
        listen_address: 0.0.0.0:7777
        debug_listen_address: 0.0.0.0:17013
        log_level: debug
  - name: gpats
    release: garden-runc

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 1000-240000
  update_watch_time: 1000-240000
