- type: replace
  path: /releases/-
  value:
    name: grootfs
    version: 0.27.0
    url: http://bosh.io/d/github.com/cloudfoundry/grootfs-release?v=0.27.0
    sha1: 361e8df0e96933551bda5cfb825d3a27e6461281

- type: replace
  path: /instance_groups/name=garden/jobs/name=garden/properties/garden/default_container_rootfs?
  value: docker:///busybox:1.27.2

- type: replace
  path: /instance_groups/name=garden/jobs/name=garden/properties/garden/image_plugin?
  value: /var/vcap/packages/grootfs/bin/grootfs

- type: replace
  path: /instance_groups/name=garden/jobs/name=garden/properties/garden/image_plugin_extra_args?
  value: ["--config", "/var/vcap/jobs/grootfs/config/grootfs_config.yml"]

- type: replace
  path: /instance_groups/name=garden/jobs/name=garden/properties/garden/privileged_image_plugin?
  value: /var/vcap/packages/grootfs/bin/grootfs

- type: replace
  path: /instance_groups/name=garden/jobs/name=garden/properties/garden/privileged_image_plugin_extra_args?
  value: ["--config", "/var/vcap/jobs/grootfs/config/privileged_grootfs_config.yml"]

- type: replace
  path: /instance_groups/name=garden/jobs/-
  value:
    name: grootfs
    release: grootfs
    properties:
      grootfs:
        store_size_bytes: 524288000
        json_output: true
