- type: replace
  path: /instance_groups/name=garden/jobs/name=garden/properties/garden/default_container_rootfs?
  value: docker:///busybox:1.27.2

- type: replace
  path: /instance_groups/name=garden/jobs/name=garden/properties/garden/experimental_enable_grootfs?
  value: true
