- type: replace
  path: /instance_groups/0/jobs/name=garden/properties/garden/network_plugin?
  value: /var/vcap/packages/netplugin-shim/bin/netplugin-shim

- type: replace
  path: /instance_groups/0/jobs/name=garden/properties/garden/network_plugin_extra_args?
  value:
    - "--socket"
    - "/var/vcap/data/garden/tmp/netplugin-shim.sock"
